# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FizzBuzzFooBar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftHEXColors'
  pod 'IQKeyboardManagerSwift'
  pod 'DropDown'
  pod 'TTGSnackbar'
  pod 'Toast-Swift'

  # Pods for FizzBuzzFooBar

end
